### ISSUE TITLE
padStart and padEnd incorrect

### ISSUE THREAD

**Issue by AtomicNoggin** [uxitten/polyfill#1]
your implementations add a string of a given length to the initial string. 
The spec specifies that the given length is to be the total length of the final string. 

e.g. `"foo".padEnd(5,"-") // should be "foo--", not "foo-----"`

I'll try and get a pull request in tonight if I have time.

**Comment by AtomicNoggin** [comment]
Added pull request: https://github.com/uxitten/polyfill/pull/2

**Comment by uxitten** [comment]
thank you merge your pull request
