### ISSUE TITLE
String.padStart exhibits non-standard behavior when pad string arg is falsey

### ISSUE THREAD

**Issue by apm963** [uxitten/polyfill#8]
The following line:

```javascript
padString = String(padString || ' ');
```

is causing falsey inputs to be treated in a way inconsistent with browser implementations. Example below:

```javascript
Chrome implementation:
'1'.padStart(2, 0); // "01"
Polyfill:
'1'.padStart(2, 0); // " 1"
```

This probably affects other String prototypes too but I have not tested for them. I propose:

```javascript
padString = String( (typeof padString !== 'undefined' ? padString : ' ') );
```

as a potential solution.

**Comment by uxitten** [comment]
very good thank's
